config/routes.rb
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                     new_coach_session GET    /coaches/sign_in(.:format)                                                               coaches/sessions#new
#                         coach_session POST   /coaches/sign_in(.:format)                                                               coaches/sessions#create
#                 destroy_coach_session DELETE /coaches/sign_out(.:format)                                                              coaches/sessions#destroy
#                    new_coach_password GET    /coaches/password/new(.:format)                                                          devise/passwords#new
#                   edit_coach_password GET    /coaches/password/edit(.:format)                                                         devise/passwords#edit
#                        coach_password PATCH  /coaches/password(.:format)                                                              devise/passwords#update
#                                       PUT    /coaches/password(.:format)                                                              devise/passwords#update
#                                       POST   /coaches/password(.:format)                                                              devise/passwords#create
#             cancel_coach_registration GET    /coaches/cancel(.:format)                                                                coaches/registrations#cancel
#                new_coach_registration GET    /coaches/sign_up(.:format)                                                               coaches/registrations#new
#               edit_coach_registration GET    /coaches/edit(.:format)                                                                  coaches/registrations#edit
#                    coach_registration PATCH  /coaches(.:format)                                                                       coaches/registrations#update
#                                       PUT    /coaches(.:format)                                                                       coaches/registrations#update
#                                       DELETE /coaches(.:format)                                                                       coaches/registrations#destroy
#                                       POST   /coaches(.:format)                                                                       coaches/registrations#create
#                        coaches_search GET    /coaches/search(.:format)                                                                coaches/coaches#search
#                          coaches_show GET    /coaches/show(.:format)                                                                  coaches/coaches#show
#                                       GET    /user/:id(.:format)                                                                      coaches/registrations#detail
#                                signup GET    /signup(.:format)                                                                        coaches/registrations#new
#                                 login GET    /login(.:format)                                                                         coaches/sessions#new
#                                logout GET    /logout(.:format)                                                                        coaches/sessions#destroy
#                                  root GET    /                                                                                        coaches/coaches#search
#         rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                  action_mailbox/ingresses/mandrill/inbound_emails#create
#         rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                  action_mailbox/ingresses/postmark/inbound_emails#create
#            rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                     action_mailbox/ingresses/relay/inbound_emails#create
#         rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                  action_mailbox/ingresses/sendgrid/inbound_emails#create
#          rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                              action_mailbox/ingresses/mailgun/inbound_emails#create
#        rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#index
#                                       POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                 rails/conductor/action_mailbox/inbound_emails#create
#     new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                             rails/conductor/action_mailbox/inbound_emails#new
#    edit_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)                        rails/conductor/action_mailbox/inbound_emails#edit
#         rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#show
#                                       PATCH  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       PUT    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#update
#                                       DELETE /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                             rails/conductor/action_mailbox/inbound_emails#destroy
# rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                      rails/conductor/action_mailbox/reroutes#create
#                    rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#             rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#                    rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#             update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#                  rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
Rails.application.routes.draw do
  devise_for :coaches, :controllers => {
      :registrations => 'coaches/registrations',
      :sessions => 'coaches/sessions'
  }

  namespace :coaches do
    get "search",:to=>"coaches#search"
    get ":id",:to=>"coaches#show"
  end

  devise_scope :coach do
    # get "coaches/:id", :to => "coaches/registrations#detail"
    get "signup", :to => "coaches/registrations#new"
    get "login", :to => "coaches/sessions#new"
    get "logout", :to => "coaches/sessions#destroy"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'coaches/coaches#search'
end
# INSERT INTO coaches (email, encrypted_password, created_at, updated_at, name ,nickname, description, contact) VALUES ('test1@test.com', '$2a$11$1LQZC8BpPNIkqEVdaWxxnuT5DfR/yxfjkfW8w/Fwskh6j6YFKJMWu', '2019-09-25 13:25:00', '2019-09-25 13:25:00', 'テスト1', 'てすと1', '説明文', 'コンタクト');
# INSERT INTO coaches (email, encrypted_password, created_at, updated_at, name ,nickname, description, contact) VALUES ('test2@test.com', '$2a$11$1LQZC8BpPNIkqEVdaWxxnuT5DfR/yxfjkfW8w/Fwskh6j6YFKJMWu', '2019-09-25 13:25:00', '2019-09-25 13:25:00', 'テスト2', 'てすと2', '説明文', 'コンタクト');
# INSERT INTO coaches (email, encrypted_password, created_at, updated_at, name ,nickname, description, contact) VALUES ('test3@test.com', '$2a$11$1LQZC8BpPNIkqEVdaWxxnuT5DfR/yxfjkfW8w/Fwskh6j6YFKJMWu', '2019-09-25 13:25:00', '2019-09-25 13:25:00', 'テスト3', 'てすと3', '説明文', 'コンタクト');

app/models/coach.rb
class Coach < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :thumbnail, ImageUploader

  scope :where_like_name, ->(name) { where('name like ?', "%#{name}%") if name.present? }
  scope :where_like_nickname, ->(nickname) { where('nickname like ?', "%#{nickname}%") if nickname.present? }
end

app/controllers/coaches/coaches_controller.rb
# frozen_string_literal: true

class Coaches::CoachesController < ApplicationController

  def search
    @coach = Coach.new(get_params)
    @coaches = Coach.
        where_like_name(@coach.name).
        where_like_nickname(@coach.nickname).
        page(params[:page])
  end

  def show
    @coach = Coach.find(params[:id])
  end

  def get_params
    params.require(:coach).permit(:name, :nickname) if params[:coach].present?
  end
end

app/controllers/coaches/confirmations_controller.rb
# frozen_string_literal: true

class Coaches::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/coaches/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Coaches::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/coaches/passwords_controller.rb
# frozen_string_literal: true

class Coaches::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/coaches/registrations_controller.rb
# frozen_string_literal: true

class Coaches::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  #
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :name, :nickname, :description, :contact, :thumbnail])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/coaches/sessions_controller.rb
# frozen_string_literal: true

class Coaches::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/coaches/unlocks_controller.rb
# frozen_string_literal: true

class Coaches::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/coaches/coaches/search.html.erb
<% if false %>
<div class="container-fluid">
  <!-- Content here -->
  <div class="row">
    <aside class="col-12 col-md-3 col-xl-2 border-right border-sm-bottom pt-3 pb-3">
      <%= form_for @coach, url: '/coaches/search', method: :get, :html => {:class => ""} do |f| %>
        <div class="mb-4">
          <div class="form-group">
            <%= f.label :name, '名前' %>
            <%= f.text_field :name, value: @coach.name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :nickname, 'ニックネーム' %>
            <%= f.text_field :nickname, value: @coach.nickname, class: "form-control" %>
          </div>
        </div>
        <%= f.submit "検索" , class: "btn btn-primary"%>
      <% end %>
    </aside>
    <main class="col-12 col-md-9 col-xl-10 py-md-3 pl-md-5 pt-3" role="main">
      <h1 class="bd-title">コーチ一覧</h1>
      <div class="card-deck">
      <% @coaches.each do |coach| %>
        <div class="card">
          <div class="card-header">
            <div class="d-inline-block mr-3 align-middle" style="width:75px;height:75px;">
              <%= image_tag coach.thumbnail.thumb.url, class: "w-100 h-100 rounded-circle", style: "object-fit:cover;" if coach.thumbnail? %>
            </div>
            <div class="d-inline-block align-middle">
              <h5 class="card-title"><%= coach.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= coach.nickname %></h6>
            </div>
          </div>
          <div class="card-body">
            <small class="d-block" style="height: 200px;overflow: hidden;"><%= coach.description %></small>
            <%= link_to '詳細', coaches_path(coach.id), {class:"btn btn-outline-primary", role:"button"} %>
          </div>
        </div>
      <% end %>
      </div>
    </main>
  </div>
</div>
<% end %>
<div class="container-fluid my-search">
  <div class="row">
    <aside class="col-md-3 bd-sidebar pt-3 pb-3">
    <%= form_for @coach, url: '/coaches/search', method: :get, :html => {:class => ""} do |f| %>
        <div class="mb-4">
          <div class="form-group">
            <%= f.label :name, '名前' %>
            <%= f.text_field :name, value: @coach.name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :nickname, 'ニックネーム' %>
            <%= f.text_field :nickname, value: @coach.nickname, class: "form-control" %>
          </div>
        </div>
        <%= f.submit "検索" , class: "btn btn-primary"%>
      <% end %>
    </aside>
    <main class="col-md-9 bd-content">
      <h1 class="bd-title">コーチ一覧</h1>
      <div class="row">
        <% @coaches.each do |coach| %>
          <div class="col-12 col-md-6 col-xl-4 pt-3 pb-3">
            <div class="card">
              <div class="card-header">
                <div class="d-inline-block mr-3 align-middle" style="width:75px;height:75px;">
                  <%= image_tag coach.thumbnail.thumb.url, class: "w-100 h-100 rounded-circle", style: "object-fit:cover;" if coach.thumbnail? %>
                </div>
                <div class="d-inline-block align-middle">
                  <h5 class="card-title"><%= coach.name %></h5>
                  <h6 class="card-subtitle mb-2 text-muted"><%= coach.nickname %></h6>
                </div>
              </div>
              <div class="card-body">
                <small class="d-block" style="height: 200px;overflow: hidden;"><%= coach.description %></small>
                <%= link_to '詳細', coaches_path(coach.id), {class:"btn btn-outline-primary", role:"button"} %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </main>
  </div>
</div>

app/views/coaches/coaches/show.html.erb
<div class="container">
  <main class="row justify-content-center pt-3 pb-5" role="main">
    <div class="col-md-9">
    <div class="card w-100 mr-md-3 ml-md-3">

      <div class="card-header bg-white border-primary" style="border-bottom: 3px solid">
        <div>
          <div><h3 class="mb-0">コーチについて</h3></div>
        </div>
      </div>

      <div class="card-header border-bottom-0">
        <div>
          <div><h5 class="mb-0">基本情報</h5></div>
        </div>
      </div>
      <div class="card-body">
        <div>
          <div class="d-inline-block mr-3 align-middle" style="width:75px;height:75px;">
            <%= image_tag @coach.thumbnail.thumb.url, class: "w-100 h-100 rounded-circle", style: "object-fit:cover;" if @coach.thumbnail? %>
          </div>
          <div class="d-inline-block align-middle">
            <h5 class="card-title"><%= @coach.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= @coach.nickname %></h6>
          </div>
        </div>
      </div>

      <div class="card-header border-bottom-0">
        <div>
          <div><h5 class="mb-0">紹介文</h5></div>
        </div>
      </div>
      <div class="card-body">
        <%= @coach.description %>
      </div>

      <div class="card-header border-bottom-0">
        <div>
          <div><h5 class="mb-0">申込方法</h5></div>
        </div>
      </div>
      <div class="card-body">
        <%= @coach.contact %><br><br>
        ※ 利用状況把握のため、<%= link_to "申込フォーム", "https://forms.gle/aEKQ54dKiCTjVqDz7" %>記入をお願いします。
      </div>

    </div>
    </div>
  </main>
</div>